
name: Build Status

on:
  [ "push", "pull_request" ]

jobs:
  build:
    name: Build test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 coverage
        pip install -r requirements.txt
    - name: Run unit tests
      run: |
        python --version
        python -m unittest
    - name: Run convention tests
      run: python -m flake8 modi tests
    - name: Run coverage tests
      run: coverage run --source=modi.module setup.py test
    - name: Code Climate Coverage Action
      uses: paambaati/codeclimate-action@v2.6.0
      env:
        CC_TEST_REPORTER_ID: 128d39bfc4c48bd3d012d1b4db713df3219ea4bead124a32e780aa44a1e09690
      with:
        # Coverage command to execute
        coverageCommand: coverage xml
        coverageLocations: ./coverage.xml:coverage.py
