
name: Coverage (Coveralls)

on: [ pull_request ]

jobs:
  # Runs coverage and upload it
  coverage:
    name: Coverage Test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    # Runs a set of commands using the runners shell
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coveralls
        pip install -r requirements.txt
    - name: Run coverage
      env:
        COVERALLS_REPO_TOKEN: qwWtAcClZM9uduEHYvmoPGhtwhElXGTbU
      run: |
        coverage run --source=modi.module setup.py test
        coveralls

