# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Handle Pull Request

on: pull_request

jobs:
  handle:
    name: Handle Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request size labeler
        uses: CodelyTV/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_max_size: '10'
          s_max_size: '100'
          m_max_size: '500'
          l_max_size: '1000'
          fail_if_xl: 'false'
          message_if_xl: "Great Work!! It's gonna take ages to review this. :cry:"
